### ISSUE TITLE
IBM_DB not working

### ISSUE THREAD

**Issue by asrock37** [py2exe/py2exe#104]
connection on accessing db2 working fine when using python, but if I am going to py2exe I got this error when executing the compile application using py2exe:

Traceback (most recent call last):
  File "boot_common.py", line 46, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "ctypes\__init__.pyc", line 7, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "<loader>", line 10, in <module>
  File "<loader>", line 8, in __load
ImportError: (DLL load failed while importing _ctypes: The specified module could not be found.) 'E:\\FMR\\fmr_Agent\\_ctypes.pyd'
Traceback (most recent call last):
  File "fmr_2021.py", line 10, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "src\fmr2021_99_Main.pyc", line 6, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "myLib\dbConnect.pyc", line 7, in <module>
ModuleNotFoundError: No module named 'ibm_db'

**Comment by albertosottile** [comment]
Hello,

most likely, `ibm_db` requires a hook to be correctly used with `py2exe`. However, I do not know the library nor IBM DB2 at all and I cannot write one alone. 

If you could provide here at least a minimal code that can be used to test the package, that would be already great. However, I am afraid a standalone test might be difficult or impossible as an external database server might be required. 

For now, I am leaving this open in case you or someone else have an idea on how to implement and test this.

**Comment by asrock37** [comment]
okey, thanks for your time, i am still looking for possible reason why it did not included or execute correctly, maybe there are some factors that needed to be consider.

**Comment by asrock37** [comment]
hi @albertosottile,

i made it included the ibm-db.pyd in the library.zip but the clidriver not found in library.zip, how to include the clidriver to the zipfile? 

Thanks in advance

**Comment by asrock37** [comment]
Hi @albertosottile 

I can now connect using the PyInstaller with this additional parameters:

- binaries=[('C:\\users\\xxxxxx\\.virtualenvs\\development\\lib\\site-packages\\ibm_db_dlls\\ibm_db.dll', '.\\ibm_db_dlls')],
- datas=[('C:\\users\\xxxxxx\\.virtualenvs\\development\\lib\\site-packages\\clidriver', '.\\clidriver')],
- hookspath=['C:\\users\\xxxxxx\\.virtualenvs\\development\\lib\\site-packages\\clidriver;.\\clidriver'],

But I want the Py2exe, because it is more faster to load than Pyinstaller. Can you give me an inputs on how to add those parameters in py2exe setup file. 

Thanks in advance once again

**Comment by albertosottile** [comment]
I am not sure what exacrly is needed bythe package to function. If it is just the `ibm_db.dll` library, you could write a hook very similar to the one used for `shapely`: https://github.com/py2exe/py2exe/blob/1071a13835d9aa9874d5868a2763366479869307/py2exe/hooks.py#L678-L682

The hook code becomes a little more complicated in case you need to copy the library file in a specific subfolder or in case you need to copy also extra files. In general, the methods `finder.add_libfile` and `finder.add_datadirectory` are also available to assist you.

I hope this helps and good luck. I would welcome a PR if you succeed in this endeavor.

**Comment by albertosottile** [comment]
Closing this as no further input was provided in the past month. I hope you succeeded in your endeavor.
