### ISSUE TITLE
SciPy DLLs not found by dllfinder

### ISSUE THREAD

**Issue by urishab** [py2exe/py2exe#108]
Using py2exe with a simple script using SciPy ends up with a crash of the executable because it is unable to find some required DLLs.
I see the custom hook in the code but for some reason it is not enough.
Adding SciPy to Packages does not solve the issue.

However copying all DLLs from **pyenv\Lib\site-packages\scipy\.libs** into the **dist** folder does solve the issue

**Python3.8, 
py2exe 0.10.4.1**

Requierments:
```
scipy==1.7.1
py2exe==0.10.4.1
```

script:
```
from scipy.ndimage.filters import gaussian_filter
print('working')

```
py2exe script:
```
from distutils.core import setup
import py2exe #@UnusedImport

setup(
    console = [{"script": "test_scipy.py",},],
    options = {"py2exe": {"packages": ['scipy']}},
)
```

Output:
```
Traceback (most recent call last):
  File "test_scipy.py", line 1, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "scipy\ndimage\__init__.pyc", line 153, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "scipy\ndimage\interpolation.pyc", line 37, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "scipy\special\__init__.pyc", line 643, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "<loader>", line 10, in <module>
  File "<loader>", line 8, in __load
ImportError: (DLL load failed while importing _ufuncs: The specified module could not be found.) 'C:\\Projects\\test\\code\\dist\\scipy.special._ufuncs.pyd'
```

**Comment by albertosottile** [comment]
You need to unzip the wheel file before installing them via pip. Unfortunately GitHub Actions still does not allow to serve artifacts without zipping them.

**Comment by urishab** [comment]
Thanks, I didnt know that.
Its strange that it doesnt throw any error about that!

Anyway, the fix works for me.
Of course it would be better to detect the correct DLLs to add but this is much better than not working.

thanks again
