### ISSUE TITLE
FileNotFoundError - how to include data files in library.zip archive?

### ISSUE THREAD

**Issue by nightwnvol** [py2exe/py2exe#119]
I am trying to compile an exe which requires [dipy](https://dipy.org/) library. It compiles but when i try to run it this error comes up:
```
Traceback (most recent call last):
  File "noddi.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "zipextimporter.pyc", line 97, in load_module
  File "<frozen zipimport>", line 259, in load_module
  File "amico\__init__.pyc", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "zipextimporter.pyc", line 97, in load_module
  File "<frozen zipimport>", line 259, in load_module
  File "amico\core.pyc", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "zipextimporter.pyc", line 97, in load_module
  File "<frozen zipimport>", line 259, in load_module
  File "amico\lut.pyc", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "zipextimporter.pyc", line 97, in load_module
  File "<frozen zipimport>", line 259, in load_module
  File "dipy\data\__init__.pyc", line 197, in <module>
  File "dipy\data\__init__.pyc", line 190, in get_sphere
  File "numpy\lib\npyio.pyc", line 417, in load
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\..\\dist\\library.zip\\dipy\\data\\files\\repulsion724.npz'
```
Here's my `setup.py` file:
```
from distutils.core import setup
import py2exe

setup(
    console=['noddi.py'],
    options={
        'py2exe': {
            'includes': ['h5py.defs', 'h5py.utils', 'h5py.h5ac', 'h5py._proxy'],
            'bundle_files': 1
        }
    }
)
```
I tried to use the `data_files` option to include the content of the `dipy\data\files\` folder inside the `library.zip` archive but it does not work, instead it copy all the files directly in the `dist` folder.

### EDIT
Actually, I was able to manually append the missing files to the `library.zip` archive with the script below, but I receive the same error message.
```
dipy_files_path = 'C:\\Users\\..\\Lib\\site-packages\\dipy\\data\\files'
dipy_files = os.listdir(dipy_files_path)
archive = zipfile.ZipFile('dist\\library.zip', 'a', zipfile.ZIP_DEFLATED)

for f in dipy_files:
    archive.write(os.path.join(dipy_files_path, f), 'dipy\\data\\files\\' + f)
    
archive.close()
```

**Comment by albertosottile** [comment]
Hi, thanks for reporting this. As you already noticed, putting your data files in the zip archive is only half of the problem. The other half is that your Python dependencies have to load them from there, which is often not supported (as in this case).

You now have two choices: the easiest would be to switch from `'bundle_files': 1` to `'bundle_files': 3`, in which the data files will be available directly in the app folder (the supported case for your library). Alternatively, you can look at the code of `npyio.py` and patch it to support loading of data files from a zip archive.

**Comment by albertosottile** [comment]
In general, though, the answer to your question is included in this hook for `selenium`:
https://github.com/py2exe/py2exe/blob/fdde3fa18fac86304f2e6d3279d3c487a88dabd1/py2exe/hooks.py#L701-L710

`DllFinder` provides a `add_datafile_to_zip(name, path)` method that does exactly what you asked.

**Comment by nightwnvol** [comment]
Hi, thanks for replying. Thanks for providing me the `add_datafile_to_zip` method. However, I tried to setting the `bundle_files: 3` option but it still does not work (the `dipy` folder and all its necessary data files are still copied in the `library.zip` archive and not in the `dist` folder).

**Comment by albertosottile** [comment]
If you want to use `bundle_files: 3`, then you should either copy the data file by hand (for testing purposes) or use the `add_datadirectory` method as in https://github.com/py2exe/py2exe/blob/fdde3fa18fac86304f2e6d3279d3c487a88dabd1/py2exe/hooks.py#L284-L290

**Comment by nightwnvol** [comment]
I did it, I used the `add_datadirecotry` method you mentioned togheter with `bundle_files: 3` but it still does not run. It continues trying to load the necessary data files from the `library.zip` archive.

**Comment by albertosottile** [comment]
Yes, as I mentioned before, adding the files to the bundle is only half of the problem: the other half is instructing your dependencies to use them. 

In this case, `dipy` relies on `__file__` to get the data file path:
https://github.com/dipy/dipy/blob/be956a529465b28085f8fc435a756947ddee1c89/dipy/data/__init__.py#L65

Patching this code should allow you to easily retrieve data files when `bundle_files: 3`.

**Comment by nightwnvol** [comment]
Oh thanks, now I get it.
