### ISSUE TITLE
semantic_version now uses importlib and probably requires a py2exe hook

### ISSUE THREAD

**Issue by Athanasius** [py2exe/py2exe#126]
semantic_version 2.8.5 / `semantic_version/__init__.py`:
```python
# -*- coding: utf-8 -*-
# Copyright (c) The python-semanticversion project
# This code is distributed under the two-clause BSD License.


from .base import compare, match, validate, SimpleSpec, NpmSpec, Spec, SpecItem, Version


__author__ = "Raphaël Barrois <raphael.barrois+semver@polytechnique.org>"
__version__ = '2.8.5'
```
That works with py2exe, no problem.

semantic_version 2.9.0 / `semantic_version/__init__.py`:
```python
# -*- coding: utf-8 -*-
# Copyright (c) The python-semanticversion project
# This code is distributed under the two-clause BSD License.


from .base import compare, match, validate, SimpleSpec, NpmSpec, Spec, SpecItem, Version


__author__ = "Raphaël Barrois <raphael.barrois+semver@polytechnique.org>"
try:
    # Python 3.8+
    from importlib.metadata import version

    __version__ = version("semantic_version")
except ImportError:
    import pkg_resources

    __version__ = pkg_resources.get_distribution("semantic_version").version
```
This does not work with py2exe because py2exe only packages the necessary files from the `semantic_version/` directory, and nothing from the accompanying `semantic_version-2.9.0.dist-info/` directory (NB: 2.8.5 has an equivalent).  This then leads to the error:

```python
Traceback (most recent call last):
  File "semantic_version\__init__.pyc", line 14, in <module>
  File "importlib\metadata\__init__.pyc", line 955, in version
  File "importlib\metadata\__init__.pyc", line 928, in distribution
  File "importlib\metadata\__init__.pyc", line 518, in from_name
importlib.metadata.PackageNotFoundError: No package metadata was found for semantic_version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "EDMarketConnector.py", line 55, in <module>
  File "killswitch.pyc", line 12, in <module>
  File "semantic_version\__init__.pyc", line 18, in <module>
  File "pkg_resources\__init__.pyc", line 466, in get_distribution
  File "pkg_resources\__init__.pyc", line 342, in get_provider
  File "pkg_resources\__init__.pyc", line 886, in require
  File "pkg_resources\__init__.pyc", line 772, in resolve
pkg_resources.DistributionNotFound: The 'semantic_version' distribution was not found and is required by the application```

**Comment by albertosottile** [comment]
Looks like it's time to embed metadata in the archive... I gave it a try, could you download artifacts from https://github.com/py2exe/py2exe/actions/runs/1834121951, test this on your system and report here if you still have this issue? Thank you.

**Comment by Athanasius** [comment]
I'll try this out some time on Monday latest, thanks.

**Comment by Athanasius** [comment]
Now there's another issue.  I recall you added a hook to pull in `pkg_resources` for `semantic_version` before.  But then you also made some change requiring any sub-packages be explicitly included.  There is this in the 'missing modules' output:

```
? pkg_resources.extern.packaging      imported from pkg_resources
```

but I see this on the `import semantic_version` in our code:

```python
Traceback (most recent call last):
  File "EDMarketConnector.py", line 2003, in <module>
  File "EDMarketConnector.py", line 448, in __init__
  File "infi\systray\__init__.pyc", line 1, in <module>
  File "pkg_resources\__init__.pyc", line 75, in <module>
  File "pkg_resources\extern\__init__.pyc", line 52, in create_module
  File "pkg_resources\extern\__init__.pyc", line 44, in load_module
ImportError: The 'packaging' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
  ```

No 'packaging' in the resultant library.zip despite that mention of `pkg_resources.extern.packaging`.
```
>python setup.py py2exe
Git short hash: 3cee7bc1
C:\Users\Athan\Documents\Devel\EDMarketConnector\venv\lib\site-packages\setuptools\dist.py:501: UserWarning: Normalizing '5.3.0-beta11+3cee7bc1' to '5.3.0b11+3cee7bc1'
  warnings.warn(tmpl.format(**locals()))
running py2exe

  63 missing Modules
  ------------------
? AppKit                              imported from hotkey, monitor, protocol, theme
? ApplicationServices                 imported from prefs
? Cookie                              imported from requests.compat
? Foundation                          imported from config.darwin, l10n, prefs
? OpenSSL.SSL                         imported from urllib3.contrib.pyopenssl
? OpenSSL.crypto                      imported from urllib3.contrib.pyopenssl
? Queue                               imported from urllib3.util.queue
? ScriptingBridge                     imported from prefs
? StringIO                            imported from requests.compat, urllib3.packages.six
? __builtin__                         imported from pkg_resources._vendor.pyparsing
? __main__                            imported from bdb, pdb, pkg_resources
? _frozen_importlib                   imported from importlib, importlib.abc, zipimport
? _frozen_importlib_external          imported from importlib, importlib._bootstrap, importlib.abc, zipimport
? _watchdog_fsevents                  imported from watchdog.observers.fsevents
? _winreg                             imported from pkg_resources._vendor.appdirs, platform, requests.utils
? assets.FREQUENCIES                  imported from charset_normalizer.cd, charset_normalizer.constant
? brotli                              imported from urllib3.response, urllib3.util.request
? chardet                             imported from requests, requests.compat, requests.packages
? collections.Callable                imported from requests.compat
? collections.Iterable                imported from pkg_resources._vendor.pyparsing
? collections.Mapping                 imported from requests.compat, urllib3._collections
? collections.MutableMapping          imported from pkg_resources._vendor.pyparsing, requests.compat, urllib3._collections
? com.sun                             imported from pkg_resources._vendor.appdirs
? com.sun.jna                         imported from pkg_resources._vendor.appdirs
? com.sun.jna.platform                imported from pkg_resources._vendor.appdirs
? cookielib                           imported from requests.compat
? cryptography                        imported from requests, urllib3.contrib.pyopenssl
? cryptography.hazmat.backends.openssl imported from urllib3.contrib.pyopenssl
? cryptography.hazmat.backends.openssl.x509 imported from urllib3.contrib.pyopenssl
? cryptography.x509                   imported from urllib3.contrib.pyopenssl
? cryptography.x509.extensions        imported from urllib3.contrib.pyopenssl
? dummy_threading                     imported from requests.cookies
? eddn                                imported from __main__
? java.lang                           imported from platform
? logging.TRACE                       imported from __main__
? objc                                imported from hotkey, prefs, protocol, update
? ordereddict                         imported from pkg_resources._vendor.pyparsing
? org.python.core                     imported from copy, pickle
? os.path                             imported from __main__, charset_normalizer.api, collate, commodity, ctypes._aix, dashboard, l10n, loadout, monitor, os, outfitting, pkg_resources, pkgutil, prefs, py_compile, requests.adapters, sysconfig, td, theme, tracemalloc, update, watchdog.events, watchdog.observers.kqueue, watchdog.observers.read_directory_changes
? packages.six.moves                  imported from urllib3.connectionpool, urllib3.util.queue, urllib3.util.response
? packages.six.moves.http_client      imported from urllib3.connection, urllib3.exceptions
? packages.six.moves.urllib.parse     imported from urllib3.poolmanager, urllib3.request
? pep517                              imported from importlib.metadata
? pkg_resources                       imported from semantic_version
? pkg_resources.extern.appdirs        imported from pkg_resources
? pkg_resources.extern.packaging      imported from pkg_resources
? readline                            imported from cmd, code, pdb
? socks                               imported from urllib3.contrib.socks
? unicodedata2                        imported from charset_normalizer.utils
? urllib.getproxies                   imported from requests.compat
? urllib.getproxies_environment       imported from requests.compat
? urllib.proxy_bypass                 imported from requests.compat
? urllib.proxy_bypass_environment     imported from requests.compat
? urllib.quote                        imported from requests.compat
? urllib.quote_plus                   imported from requests.compat
? urllib.unquote                      imported from requests.compat
? urllib.unquote_plus                 imported from requests.compat
? urllib.urlencode                    imported from requests.compat
? urllib2                             imported from requests.compat
? urlparse                            imported from requests.compat
? util.SKIPPABLE_HEADERS              imported from urllib3.connection
? util.SKIP_HEADER                    imported from urllib3.connection
? win32com.gen_py                     imported from win32com
Building 'dist.win32\EDMC.exe'.
Building 'dist.win32\EDMarketConnector.exe'.
Building shared code archive 'dist.win32\library.zip'.
Copy c:\program files (x86)\python310-32\python310.dll to dist.win32
Copy C:\Program Files (x86)\Python310-32\DLLs\_bz2.pyd to dist.win32\_bz2.pyd
Copy C:\Program Files (x86)\Python310-32\DLLs\_lzma.pyd to dist.win32\_lzma.pyd
Copy C:\Program Files (x86)\Python310-32\DLLs\unicodedata.pyd to dist.win32\unicodedata.pyd
Copy C:\Program Files (x86)\Python310-32\DLLs\_hashlib.pyd to dist.win32\_hashlib.pyd
Copy C:\Program Files (x86)\Python310-32\DLLs\_decimal.pyd to dist.win32\_decimal.pyd
Copy C:\Program Files (x86)\Python310-32\DLLs\_socket.pyd to dist.win32\_socket.pyd
Copy C:\Program Files (x86)\Python310-32\DLLs\select.pyd to dist.win32\select.pyd
Copy C:\Program Files (x86)\Python310-32\DLLs\pyexpat.pyd to dist.win32\pyexpat.pyd
Copy C:\Program Files (x86)\Python310-32\DLLs\_ssl.pyd to dist.win32\_ssl.pyd
Copy C:\Program Files (x86)\Python310-32\DLLs\_ctypes.pyd to dist.win32\_ctypes.pyd
Copy C:\Program Files (x86)\Python310-32\DLLs\_queue.pyd to dist.win32\_queue.pyd
Copy C:\Users\Athan\Documents\Devel\EDMarketConnector\venv\lib\site-packages\win32\_win32sysloader.cp310-win32.pyd to dist.win32\_win32sysloader.pyd
Copy C:\Users\Athan\Documents\Devel\EDMarketConnector\venv\lib\site-packages\win32\win32api.cp310-win32.pyd to dist.win32\win32api.pyd
Copy C:\Users\Athan\Documents\Devel\EDMarketConnector\venv\lib\site-packages\win32comext\shell\shell.cp310-win32.pyd to dist.win32\win32com.shell.shell.pyd
Copy C:\Program Files (x86)\Python310-32\DLLs\_uuid.pyd to dist.win32\_uuid.pyd
Copy C:\Program Files (x86)\Python310-32\DLLs\_sqlite3.pyd to dist.win32\_sqlite3.pyd
Copy C:\Users\Athan\Documents\Devel\EDMarketConnector\venv\lib\site-packages\win32\win32evtlog.cp310-win32.pyd to dist.win32\win32evtlog.pyd
Copy C:\Program Files (x86)\Python310-32\DLLs\_tkinter.pyd to dist.win32\_tkinter.pyd
Copy C:\Program Files (x86)\Python310-32\DLLs\winsound.pyd to dist.win32\winsound.pyd
Copy C:\Program Files (x86)\Python310-32\DLLs\_elementtree.pyd to dist.win32\_elementtree.pyd
Copy DLL C:\Program Files (x86)\Python310-32\DLLs\tk86t.dll to dist.win32\
Copy DLL C:\Program Files (x86)\Python310-32\DLLs\sqlite3.dll to dist.win32\
Copy DLL C:\Program Files (x86)\Python310-32\DLLs\libffi-7.dll to dist.win32\
Copy DLL C:\Program Files (x86)\Python310-32\DLLs\libcrypto-1_1.dll to dist.win32\
Copy DLL C:\Program Files (x86)\Python310-32\DLLs\libssl-1_1.dll to dist.win32\
Copy DLL C:\Program Files (x86)\Python310-32\DLLs\tcl86t.dll to dist.win32\
Copy lib file C:\Users\Athan\Documents\Devel\EDMarketConnector\venv\lib\site-packages\certifi\cacert.pem to dist.win32\
Copy ExtensionDLL C:\Users\Athan\Documents\Devel\EDMarketConnector\venv\lib\site-packages\pywin32_system32\pythoncom310.dll to dist.win32\
Copy ExtensionDLL C:\Users\Athan\Documents\Devel\EDMarketConnector\venv\lib\site-packages\pywin32_system32\pywintypes310.dll to dist.win32\
```

**Comment by albertosottile** [comment]
I am confused... `packaging` is indeed added in the bundle (see https://github.com/py2exe/py2exe/commit/9e9cc9af30ba30839765a415cd6aa9b0c6616efa#). Because we embed the `_vendor` folder, the `extern` package should be irrelevant and `pkg_resources` should always use the embedded version.

Furthermore, I added a test in the CI that reproduces exactly this issue (https://github.com/py2exe/py2exe/blob/egginfo/tests/functional/metadata_test/metadata_test.py) and it is pass in the build I sent to you (https://github.com/py2exe/py2exe/runs/5168132483?check_suite_focus=true#step:10:760).

**Comment by Athanasius** [comment]
Hmmm, yes, there's something else at play here, as I just did a bare program:

```python
import semantic_version

print("Got to the print")
```
and a basic py2exe build, and that works.  Let me look deeper into the actual application setup.py etc and get back to you.

**Comment by Athanasius** [comment]
Ah, duh, it's infi.systray being a pain now, not semantic_version.

**Comment by albertosottile** [comment]
Interesting, I thought that was fixed for good... Nevertheless, I still do not understand the error. Could you check the content of the `pkg_resources\_vendor\` folder of your `library.zip` file?

**Comment by Athanasius** [comment]
> Interesting, I thought that was fixed for good... Nevertheless, I still do not understand the error. Could you check the content of the `pkg_resources\_vendor\` folder of your `library.zip` file?

```
0$ unzip -l dist.win32/library.zip | fgrep _vendor
   198760  2022-02-12 18:58   pkg_resources/_vendor/pyparsing.pyc
    20188  2022-02-12 18:58   pkg_resources/_vendor/appdirs.pyc
      127  2022-02-12 18:58   pkg_resources/_vendor/__init__.pyc
0$ ls venv/Lib/site-packages/pkg_resources/_vendor/
__init__.py  __pycache__/  appdirs.py*  packaging/  pyparsing.py
```

**Comment by albertosottile** [comment]
So the `packaging` folder is indeed there. Because of what you found, though, I think we have to abandon this issue and reopen #88... :/

**Comment by Athanasius** [comment]
Let me just check that semantic_version definitely works if I rip the infi.systray stuff out.  It should, as semantic_version is imported much earlier.

**Comment by Athanasius** [comment]
Checking `pip freeze`:

```
py2exe @ file:///C:/Users/Athan/Downloads/Devel/Python/py2exe/py2exe-0.11.1.0-cp
310-cp310-win32.whl
semantic-version==2.9.0
```
and a rebuild yields a working .exe - so yes, let's close this and head over to #88

**Comment by albertosottile** [comment]
Fixed in 0.11.1.0.
