### ISSUE TITLE
opencv (opencv-python) package no longer works with py2exe

### ISSUE THREAD

**Issue by urishab** [py2exe/py2exe#147]
opencv-python is a package that has precompiled binaries for opencv for python.
Since version 4.5.4.58 it is no longer compatible with py2exe.
With version 4.5.4.58 py2exe fails while bundling the application with the following:
```

  File "C:\Projects\FluHema\pyenv\lib\site-packages\py2exe\vendor\modulefinder.py", line 220, in import_hook
    self.ensure_fromlist(m, fromlist)

  File "C:\Projects\FluHema\pyenv\lib\site-packages\py2exe\vendor\modulefinder.py", line 310, in ensure_fromlist
    self.ensure_fromlist(m, all, 1)

  File "C:\Projects\FluHema\pyenv\lib\site-packages\py2exe\vendor\modulefinder.py", line 315, in ensure_fromlist
    raise ImportError("No module named " + subname)

ImportError: No module named cv2.config-3.9
```

With the most recent version of opencv-python, py2exe succeeds in bundling the app but the app later fails during runtime failing to find "config.py" when importing cv2

**Comment by albertosottile** [comment]
Hello, thanks for reporting this. Could you provide here a minimal script and `setup.py` file that I can use to test this issue?

**Comment by urishab** [comment]
python 3.9.13
pip install py2exe opencv-python
pip freeze:
```
cachetools==5.2.0
future==0.18.2
numpy==1.23.2
opencv-python==4.6.0.66
pefile==2022.5.30
py2exe==0.11.1.1
```
test.py:
```
import cv2
print('hello')
```

py2exe_test.py:
```
from distutils.core import setup
import py2exe #@UnusedImport
setup(console = [{  "script": "test.py", }, ],)
```
run:
python py2exe_test.py py2exe
dist\test.exe

result:
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "cv2\__init__.pyc", line 181, in <module>
  File "cv2\__init__.pyc", line 111, in bootstrap
  File "cv2\__init__.pyc", line 109, in load_first_config
ImportError: OpenCV loader: missing configuration file: ['config.py']. Check OpenCV installation.
```

**Comment by UlisesRN01** [comment]
Same bug with 

Python 3.10

py2exe 0.12.0.1
opencv-python 4.6.0.66

Any solution?

**Comment by albertosottile** [comment]
I gave a look at this issue and unfortunately I do not have good news. It is quite easy for me to add the `config.py` and `config-3.py` files in the bundle's archive, but then `opencv-python` wants to have direct filesystem access to them. See https://github.com/opencv/opencv/blob/b77330bafc497ddf65074783c0e3fb989604b555/modules/python/package/cv2/__init__.py#L99-L109 .

Essentially, `opencv` is now incompatible with [zipimport](https://docs.python.org/3/library/zipimport.html), a key requirement to function with `py2exe`. This leaves us two options:
- implement a hack on the `py2exe` side, similar to what was done for `matplotlib` [here](https://github.com/py2exe/py2exe/blob/7c04d7ff20e763991993ccc6a8b49d918718e62d/py2exe/hooks.py#L367) that bypasses the initialization mechanism of `opencv` and provides an alternative compatible with `zipimport` (I guess `cv2.bootstrap` would have to be completely reimplemented)
- report this issue upstream, so that they can provide an alternative mechanism to load/pass these configuration files (perhaps one already exists, but I am not aware of it)

Unfortunately, I do not have the capacity for pursuing the first option (I did this for `matplotlib` as that package is definitely more popular, and the solution was indeed not that complicated). Therefore, I would encourage you to ask for help upstream, for the moment. In any case, I am of course willing to review PRs regarding this issue.
