### ISSUE TITLE
The system cannot find the path specified: `dist\library.zip\PySide6`

### ISSUE THREAD

**Issue by bersbersbers** [py2exe/py2exe#158]
`demo.py`:
```python
"""Demo"""
from PySide6.QtWidgets import QApplication, QMainWindow

application = QApplication()
window = QMainWindow()
window.show()
application.exec()
```

`demo.bat`:
```bat
@echo off
pip install pyside6-essentials
python demo.py
python -c "import py2exe; py2exe.freeze(console=['demo.py'])"
dist\demo.exe
```

Output:
```
[...]
Building 'dist\demo.exe'.
Traceback (most recent call last):
  File "demo.py", line 2, in <module>
    from PySide6.QtWidgets import QApplication, QMainWindow
  File "PySide6\__init__.pyc", line 123, in <module>
  File "PySide6\__init__.pyc", line 111, in _find_all_qt_modules
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Code\\Project\\dist\\library.zip\\PySide6'
```

**Comment by bersbersbers** [comment]
Ah, I see - thanks! Does this mean you don't need `windeployqt` at all? Very cool, I was not aware the dll files were in the PyPI package.

**Comment by albertosottile** [comment]
Yep, the wheels embed all the pyd/dll files already. As a matter of fact, usually I prune the libraries I do not need from the bundle. I guess the introduction of the `essential` wheels will mitigate this problem.

**Comment by pavel-demin** [comment]
For information. It seems this issue is now fixed with the latest versions of py2exe, PySide and Python.

While I was previously able to reproduce this issue, now everything works perfectly and I can create executables using Python 3.13.6, PySide 6.9.1 and py2exe 0.14.0.0.
