### ISSUE TITLE
matplotlib and wx

### ISSUE THREAD

**Issue by infinity77** [py2exe/py2exe#169]
This is somehow related to #71 .

The hook for matplotlib looks like this:

![image](https://user-images.githubusercontent.com/8988321/208370996-c9089ed7-4d1f-493e-9258-8dc367cacbfc.png)

How about I am using wxPython for my interface?

This ends up putting "wx" in the list of excluded packages, and of course py2exe bombs out like this:

Traceback (most recent call last):
  File "C:\Users\Whatever\MyProject\setup.py", line 1404, in <module>
    BuildPy2Exe(architecture)
  File "C:\Users\Whatever\MyProject\setup.py", line 739, in BuildPy2Exe
    setup(
  File "C:\Users\Whatever\python-3.9.10.amd64\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
    return run_commands(dist)
  File "C:\Users\Whatever\python-3.9.10.amd64\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
    dist.run_commands()
  File "C:\Users\Whatever\python-3.9.10.amd64\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "C:\Users\Whatever\python-3.9.10.amd64\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
    cmd_obj.run()
  File "C:\Users\Whatever\python-3.9.10.amd64\lib\site-packages\py2exe\distutils_buildexe.py", line 204, in run
    self._run()
  File "C:\Users\Whatever\python-3.9.10.amd64\lib\site-packages\py2exe\distutils_buildexe.py", line 284, in _run
    builder.analyze()
  File "C:\Users\Whatever\python-3.9.10.amd64\lib\site-packages\py2exe\runtime.py", line 176, in analyze
    mf.import_hook(modname)
  File "C:\Users\Whatever\python-3.9.10.amd64\lib\site-packages\py2exe\vendor\modulefinder.py", line 215, in import_hook
    q, tail = self.find_head_package(parent, name)
  File "C:\Users\Whatever\python-3.9.10.amd64\lib\site-packages\py2exe\vendor\modulefinder.py", line 284, in find_head_package
    raise ImportError(f'Module {name} is in the "excludes" list')
ImportError: Module wx is in the "excludes" list

**Comment by albertosottile** [comment]
Hi, thanks for reporting this. If you look at blame in that area, you will see that call to `excludes` was added 8 years ago, way before I started using `py2exe`. I have no idea if that exclusion is still needed nowadays. My question for you would be: can you try to comment that line and freeze your code? Does it work after?

**Comment by infinity77** [comment]
Hi, not looking to blame anyone, this is open source after all. It just seemed weird to preemptively exclude wx as it is one of the main backends of matplotlib.

it works if I comment out that line.

**Comment by albertosottile** [comment]
Sorry, with blame I meant `git blame` -> https://github.com/py2exe/py2exe/blame/master/py2exe/hooks.py#L379 

Perhaps the name of this feature is too harsh... anyway, I did not feel any actual blame from your side, no worries.

Thanks for confirming that `matplotlib` works also with `wx`. I will give a look about patching this, but I am away from home for the holidays so this might take a while.

**Comment by zobac** [comment]
I've found that if I put wx first in the includes list (before matplotlib) it will be ignored in the excludes list when added by matplotlib.

**Comment by albertosottile** [comment]
Fixed in 0.13.0.1
