### ISSUE TITLE
SystemError: <method 'load_module' of 'zipimport.zipimporter' objects> returned NULL without setting an error

### ISSUE THREAD

**Issue by jossieb** [py2exe/py2exe#50]
Hi,

When using a Py2Exe created exe in a Windows 7 environment I get a system error on webdav3\client.pyc.
What can I do to overcome this error?

Pyton code:
-------------
from webdav3.client import Client
....
    options = {
        'webdav_hostname': i_host,
        'webdav_login': i_login,
        'webdav_password': i_password
    }
    # use the webdav client
    client = Client(options)
    client.verify = False # To not check SSL certificates (Default = True)

Setup:
-------
Tried setup with explicit package
webdav3 is in folder ...  ...Python37\Lib\site-packages
folder is in path

from distutils.core import setup
import py2exe
    
setup( console=[{ "script": 'cpy2webdav.py'},],
       options={"py2exe": {
            "packages": ['webdav3'],}})

Error:
------
Traceback (most recent call last):
  File "cpy2webdav.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "webdav3\client.pyc", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
**SystemError: <method 'load_module' of 'zipimport.zipimporter' objects> returned NULL without setting an error**

**Comment by jossieb** [comment]
to add...

client.pyc also available in ...dist\library.zip\webdav3

**Comment by albertosottile** [comment]
The error that you are witnessing usually indicates that a package is missing from the frozen executable. Going back to https://github.com/ezhov-evgeny/webdav-client-python-3/blob/96aebf2b86814214eb6b1e089e44f2505c40093e/webdav3/client.py#L12 seems to indicate that the missing package is `lxml`.

I would change the `packages` line in your `setup.py` file. Since `webdav3` also depends on `requests` and `dateutil`, I would add them as well. So, the line should be `"packages": ['webdav3', 'lxml', 'requests', 'dateutil'],`. Please install the relevant dependencies in the build environment as well.

**Comment by jossieb** [comment]
Hi Roberto,
Thanks to your support I got it to work!!
Also needed the additional module queue in the end ;)
Regards,
Jos
