### ISSUE TITLE
importing PYD file from pycryptodome

### ISSUE THREAD

**Issue by Reks2004** [py2exe/py2exe#62]
hello, 
When pycryptodome is used with py2exe it cant import pyd file by _raw_api.pyc (bundle_files must be <3)
More info at https://python-forum.io/Thread-Py2exe-and-pycryptodome
Error log:
`Traceback (most recent call last):
File "test.py", line 9, in <module>
File "<frozen importlib._bootstrap>", line 983, in _find_and_load
File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
File "zipextimporter.pyc", line 87, in load_module
File "Crypto\Cipher\__init__.pyc", line 27, in <module>
File "<frozen importlib._bootstrap>", line 983, in _find_and_load
File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
File "zipextimporter.pyc", line 87, in load_module
File "Crypto\Cipher\_mode_ecb.pyc", line 47, in <module>
File "Crypto\Util\_raw_api.pyc", line 308, in load_pycryptodome_raw_lib
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp37-win_amd64.pyd': cannot load library 'C:\xxx\test.exe\Crypto\Util\..\Cipher\_raw_ecb.cp37-win_amd64.pyd': error 0x7e. Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\xxx\\test.exe\\Crypto\\Util\\..\\Cipher\\_raw_ecb.cp37-win_amd64.pyd', Trying '_raw_ecb.pyd': cannot load library 'C:\xxx\test.exe\Crypto\Util\..\Cipher\_raw_ecb.pyd': error 0x7e. Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\xxx\\test.exe\\Crypto\\Util\\..\\Cipher\\_raw_ecb.pyd'`

File exist and path is right

**Comment by albertosottile** [comment]
Thanks for reporting this. 
Some DLL is missing and it might or might not be part of the Python dependencies of your code. I would suggest you to try to use [dependency walker](https://stackoverflow.com/questions/14361992/dll-load-library-error-code-126/14362289#14362289) on the PYD to identify which library is not accessible from the bundle (it might be outside the PATH).

In general, could you provide me a minimal example (Python code and `setup.py`) that I could use to reproduce this issue?

**Comment by albertosottile** [comment]
So, I wrote a hook for `pycryptodome` and built new preliminary wheels that include it. You can find those wheels here: https://bintray.com/py2exe/py2exe/py2exe/0.10.1.1#files. I would really appreciate if you could install `py2exe` from these wheels and try your test again. If you are interested in what the hook does, you can check the code here: https://github.com/py2exe/py2exe/compare/develop...pycryptodome. 

Please let me know if you still experience this error with these new wheels. If this patch fixes this error, I will include it and its test in the next release of py2exe.

**Comment by albertosottile** [comment]
Fixed in [0.10.2.0](https://github.com/py2exe/py2exe/releases/tag/v0.10.2.0).
