### ISSUE TITLE
Regression: cannot put wxPython into "packages" with new version of py2exe

### ISSUE THREAD

**Issue by urishab** [py2exe/py2exe#72]
Using the 0.10 versions of py2exe, when packing a script with the option **"packages":["wx"]** I get the following error message regarding package pubsub
When switching to **py2exe-0.9.3.2-cp36-none-win_amd64.whl** this works without a problem.
Python 3.6.8 64bit
py2exe 0.10.2.1 

```
running py2exe
C:\Projects\test\pyenv\lib\site-packages\wx\lib\pubsub\__init__.py:25: wxPyDeprecationWarning: wx.lib.pubsub has been deprecated, plese migrate your code to use pypubsub, available on PyPI.
  wx.wxPyDeprecationWarning)
Traceback (most recent call last):
  File "py2exe_test.py", line 5, in <module>
    options = {"py2exe": {"packages": ['wx'],}},
  File "c:\Python36\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "c:\Python36\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "c:\Python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Projects\test\pyenv\lib\site-packages\py2exe\distutils_buildexe.py", line 192, in run
    self._run()
  File "C:\Projects\test\pyenv\lib\site-packages\py2exe\distutils_buildexe.py", line 272, in _run
    builder.analyze()
  File "C:\Projects\test\pyenv\lib\site-packages\py2exe\runtime.py", line 172, in analyze
    mf.import_package(modname)
  File "C:\Projects\test\pyenv\lib\site-packages\py2exe\mf34.py", line 76, in import_package
    self.import_package("%s.%s" % (name, modname))
  File "C:\Projects\test\pyenv\lib\site-packages\py2exe\mf34.py", line 76, in import_package
    self.import_package("%s.%s" % (name, modname))
  File "C:\Projects\test\pyenv\lib\site-packages\py2exe\mf34.py", line 76, in import_package
    self.import_package("%s.%s" % (name, modname))
  [Previous line repeated 1 more time]
  File "C:\Projects\test\pyenv\lib\site-packages\py2exe\mf34.py", line 74, in import_package
    self.safe_import_hook("%s.%s" % (name, modname))
  File "C:\Projects\test\pyenv\lib\site-packages\py2exe\mf34.py", line 114, in safe_import_hook
    self.import_hook(name, caller, fromlist, level)
  File "C:\Projects\test\pyenv\lib\site-packages\py2exe\mf34.py", line 96, in import_hook
    module = self._gcd_import(name)
  File "C:\Projects\test\pyenv\lib\site-packages\py2exe\mf34.py", line 250, in _gcd_import
    return self._find_and_load(name)
  File "C:\Projects\test\pyenv\lib\site-packages\py2exe\mf34.py", line 295, in _find_and_load
    spec = importlib.util.find_spec(name, path)
  File "c:\Python36\lib\importlib\util.py", line 88, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
  File "C:\Projects\test\pyenv\lib\site-packages\wx\lib\pubsub\core\arg1\__init__.py", line 16, in <module>
    raise RuntimeError(msg)
RuntimeError: Should not import this directly, used by pubsub.core if applicable
```

The only package I have installed is wxPython and its dependencies:
```
(pyenv) C:\Projects\test\code>pip freeze
cachetools==4.2.1
future==0.18.2
numpy==1.19.5
pefile==2019.4.18
Pillow==8.1.1
py2exe @ file:///C:/Projects/test/pyenvsetup/py2exe-0.10.2.1-cp36-none-win_amd64.whl
six==1.15.0
wxPython==4.1.1
```

my py2exe script:
```
from distutils.core import setup
import py2exe #@UnusedImport
setup(
    console = [{"script": "test.py",},],
    options = {"py2exe": {"packages": ['wx'],}},
)
```

**Comment by albertosottile** [comment]
Most likely, the new `ModuleFinder` and/or `dllfinder` is picking some deprecated module from the `wx` package when instructed to import all of it in the setup script. I would first try to mitigate this from your side.

You can either:
- remove `wx` from the list of packages, let `py2exe` figure out exactly what you need, and, if needed, just add the missing subpackages or modules instead of the whole thing
- add the offending module (`wx.lib.pubsub`) in the `excludes` key

**Comment by urishab** [comment]
I can remove wx from the list of packages but if anything is wrong in the detection of used modules then I'll end up with a missing module. It happened a few times in the past so I always add wx as a whole package.
Still, from what I've tested wx is added automatically and correctly but I might have missed something.

Trying to add 'wx.lib.pubsub' to the 'excludes' list fails with the following error:
```
running py2exe
Traceback (most recent call last):
  File "py2exe_test.py", line 7, in <module>
    options = {"py2exe": {"packages": ['wx'],"excludes":['wx.lib.pubsub']}},
  File "c:\Python36\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "c:\Python36\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "c:\Python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Projects\test\pyenv\lib\site-packages\py2exe\distutils_buildexe.py", line 192, in run
    self._run()
  File "C:\Projects\test\pyenv\lib\site-packages\py2exe\distutils_buildexe.py", line 272, in _run
    builder.analyze()
  File "C:\Projects\test\pyenv\lib\site-packages\py2exe\runtime.py", line 172, in analyze
    mf.import_package(modname)
  File "C:\Projects\test\pyenv\lib\site-packages\py2exe\mf34.py", line 76, in import_package
    self.import_package("%s.%s" % (name, modname))
  File "C:\Projects\test\pyenv\lib\site-packages\py2exe\mf34.py", line 76, in import_package
    self.import_package("%s.%s" % (name, modname))
  File "C:\Projects\test\pyenv\lib\site-packages\py2exe\mf34.py", line 68, in import_package
    self.import_hook(name)
  File "C:\Projects\test\pyenv\lib\site-packages\py2exe\mf34.py", line 96, in import_hook
    module = self._gcd_import(name)
  File "C:\Projects\test\pyenv\lib\site-packages\py2exe\mf34.py", line 246, in _gcd_import
    raise ImportError('No module named {!r}'.format(name), name=name)
ImportError: No module named 'wx.lib.pubsub'
```

**Comment by albertosottile** [comment]
This can probably be solved with a hook for `wx`. Could you provide me a test script to verify that `wx` correctly runs from the packed executable (if possible, in a CI-friendly way)? Thanks

**Comment by urishab** [comment]
I added a test script for the regression in PR #77 
It should now FAIL

**Comment by albertosottile** [comment]
Seems that adding `wx.lib.pubsub` to the `excludes` list in a hook, plus fixing `ModuleFinder` via https://github.com/py2exe/py2exe/commit/2e9587ef1db6c0eea49dff4fb697e7624b028887 to honor it did the trick! -> https://github.com/py2exe/py2exe/actions/runs/651170703

Thank you for the test PR. I will include this fix in the next patch release (probably, next weekend).

**Comment by urishab** [comment]
Great! I tested and everything works now. Thanks
