### ISSUE TITLE
library.zip: missing files in the generated archive (javascript from selenium)

### ISSUE THREAD

**Issue by rloutrel** [py2exe/py2exe#85]
I am not able to provide an example yet, but if required, please tell me, and I will try to find the time this weekend

# Steps to reproduce
**GIVEN:** A python script importing webdriver from selenium (see version in context bellow)
```python
from selenium import webdriver
```

**AND:** The build of the script ends without errors

`some python command to run the setup file returns no error`

**WHEN:** Starting the generated exe program
```batch
C:\>my_program.exe
```

**THEN:** A runtime error occurs due to a missing Javascript file from package selenium
```python
(...)
Traceback (most recent call last):
  File "<frozen zipimport>", line 177, in get_data
KeyError: 'selenium\\webdriver\\remote\\getAttribute.js'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "get_device_config.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "itf\devices\factory.pyc", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "itf\device.pyc", line 33, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "itf\channels\se_bmr.pyc", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "selenium\webdriver\__init__.pyc", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "selenium\webdriver\firefox\webdriver.pyc", line 29, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "selenium\webdriver\remote\webdriver.pyc", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "selenium\webdriver\remote\webelement.pyc", line 43, in <module>
  File "pkgutil.pyc", line 637, in get_data
  File "<frozen zipimport>", line 179, in get_data
OSError: [Errno 0] : 'selenium\\webdriver\\remote\\getAttribute.js'
```

# Ugly workaround
Insert into the library.zip file:
* selenium\webdriver\remote\getAttribute.js
* selenium\webdriver\remote\isDisplayed.js
from the original python package

# Context
```batch
C:\>python --version
Python 3.8.6
```

```batch
C:\>python -m pip freeze
bcrypt==3.2.0
cachetools==4.2.1
certifi==2020.11.8
cffi==1.14.4
chardet==3.0.4
cryptography==3.2.1
future==0.18.2
idna==2.10
junit-xml==1.9
lxml==4.6.2
netaddr==0.8.0
netifaces==0.10.9
paramiko==2.7.2
pefile==2019.4.18
py2exe==0.10.3.1
pycparser==2.20
PyNaCl==1.4.0
requests==2.25.0
selenium==3.141.0
six==1.15.0
tftpy==0.8.0
threadpool==1.3.2
urllib3==1.26.2
Yapsy==1.12.2
```

**Comment by albertosottile** [comment]
Thanks for reporting this, I can confirm you that I can reproduce the bug. I am working on an ehnancement of `dllfinder` and `runtime` to support a hook for `selenium` that adds data files directly in the zip archive, which should solve your issue. 

However, I would like to add a functional test for `selenium` in the Actions workflow. Could you provide me a test script (and a setup script) that actually uses some features of the package?

**Comment by rloutrel** [comment]
I am sorry I just realised, that my home setup will not allow to do a lot, since it is Linux (my client is using windows...).

Here is a really simplified script which should run without runtime exception, given that:
* the test environment has access to internet (here qwant)
* the test environment has the gecko driver installed (to control firefox): https://selenium-python.readthedocs.io/installation.html#drivers (there is a special hack for windows environment)

```python
from selenium import webdriver

driver = webdriver.Firefox()

driver.get('https://www.qwant.com')

query_input = driver.find_element_by_xpath('//input[@name="q"]')

assert query_input.get_attribute('type') == 'search'
```

If you want, I can borrow the windows computer of my client the next weekend and provide the requested testing setup. In the mean time could you document (or give me the link) of how your functional tests can be triggered?

**Comment by albertosottile** [comment]
Thanks, but I would prefer something that does not require to install external binaries besides the `selenium` wheels, if possible. In any case, integrate a test in the CI for this hook is not a must to release it. So, if creating a test script proves impossible or too cumbersome, this is not a blocker.

On Actions, you will find wheels that include the (tentative) fix for this issue https://github.com/py2exe/py2exe/actions/runs/714624162 . If you could download the relevant wheel archive for your system, unzip it, install the wheels via `pip`, and confirm that you do not experience this issue anymore, that would be great. I tested those wheels locally using only `from selenium import webdriver` as test script.

**Comment by rloutrel** [comment]
Nice. I can try on Tuesday.

**Comment by rloutrel** [comment]
The fix fixes the problem.

However I might create a follow-up ticket to fix other similar issues (I first try locally if there is a problem or not). Since my initial problem has been solved, it should be handle separately.

== Just for a quick overview (If I can confirm the bug, I will create a ticket, please reply there not here) ==
The package selenium is also missing some Firefox specific files (probably used to ensure pristine profiles or enabling the automation):
* selenium/webdriver/firefox/webdriver.xpi
* selenium/webdriver/firefox/webdriver_prefs.json
* selenium/webdriver/firefox/amd64/x_ignore_nofocus  (probably some workaround allowing the automation)
* selenium/webdriver/firefox/x86/x_ignore_nofocus  (probably some workaround allowing the automation)

As I do not know the structure of the other browsers (opera/chrome/edge/...), I will not check for them.

**Comment by albertosottile** [comment]
Thanks for the detailed investigation, I am indeed glad that those files are not needed. I will close this issue, then. I will release the fix in the next patch release.
