### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'libname'

### ISSUE THREAD

**Issue by crqch** [py2exe/py2exe#93]
Hello.
First of all I am new to programming in python and new to py2exe as I was using pyinstaller but with my new project it has problems to work fine.
Here's the error when trying to run python setup.py py2exe:
```python
selenium\webdriver\firefox\firefox_profile.pyc:208: SyntaxWarning: "is" with a literal. Did you mean "=="?

  35 missing Modules
  ------------------
? Cookie                              imported from requests.compat
? OpenSSL                             imported from urllib3.contrib.pyopenssl
? Queue                               imported from joblib.externals.loky.backend.compat, urllib3.util.queue
? _posixshmem                         imported from multiprocessing.resource_tracker, multiprocessing.shared_memory
? _subprocess                         imported from joblib.externals.loky.backend._win_wait, joblib.externals.loky.backend.compat_win32
? backports                           imported from urllib3.packages.ssl_match_hostname
? brotli                              imported from urllib3.response, urllib3.util.request
? collections.Callable                imported from requests.compat
? collections.Mapping                 imported from requests.compat, urllib3._collections
? collections.MutableMapping          imported from requests.compat, urllib3._collections
? cookielib                           imported from requests.compat
? cryptography                        imported from requests, urllib3.contrib.pyopenssl
? dask                                imported from joblib._dask
? distributed                         imported from joblib._dask
? dummy_threading                     imported from joblib.compressor, requests.cookies
? lz4                                 imported from joblib.compressor
? multiprocessing.forking             imported from joblib.externals.loky.backend.compat_win32, joblib.externals.loky.backend.context, joblib.externals.loky.backend.reduction
? numpy                               imported from joblib._memmapping_reducer, joblib.backports, joblib.hashing, joblib.logger, joblib.numpy_pickle, joblib.numpy_pickle_compat, joblib.numpy_pickle_utils, joblib.pool
? pickle5                             imported from joblib.externals.cloudpickle.compat
? psutil                              imported from joblib.externals.loky.backend.utils, joblib.externals.loky.process_executor
? readline                            imported from cmd, code, pdb
? resource                            imported from joblib.externals.loky.backend.fork_exec
? simplejson                          imported from requests.compat
? socks                               imported from urllib3.contrib.socks
? tornado                             imported from joblib._dask, joblib.externals.cloudpickle.cloudpickle
? typing_extensions                   imported from joblib.externals.cloudpickle.cloudpickle
? urllib.getproxies                   imported from requests.compat
? urllib.getproxies_environment       imported from requests.compat
? urllib.proxy_bypass                 imported from requests.compat
? urllib.proxy_bypass_environment     imported from requests.compat
? urllib.quote                        imported from requests.compat
? urllib.quote_plus                   imported from requests.compat
? urllib.unquote                      imported from requests.compat
? urllib.unquote_plus                 imported from requests.compat
? urllib.urlencode                    imported from requests.compat
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\prone\AppData\Roaming\Python\Python39\site-packages\py2exe\__main__.py", line 8, in <module>
    build_exe.main()
  File "C:\Users\prone\AppData\Roaming\Python\Python39\site-packages\py2exe\build_exe.py", line 138, in main
    builder.build()
  File "C:\Users\prone\AppData\Roaming\Python\Python39\site-packages\py2exe\runtime.py", line 238, in build
    self.build_exe(target, exe_path, options.libname)
AttributeError: 'Namespace' object has no attribute 'libname'```

**Comment by nullSoup** [comment]
It looks like you are using the build_exe command line interface, which as listed as not currently supported.

I recommend you create a setup.py script as described in the [tutorial](http://www.py2exe.org/index.cgi/Tutorial).

**Comment by albertosottile** [comment]
Thank you @nullSoup for providing already the correct answer for this issue. @crqch, I would encourage you to try again following the tutorial and using a `setup.py` script for your project. Hence, I am closing this issue for now.
