### ISSUE TITLE
[BUG][IMPORTANT] Inconsistent builds

### ISSUE THREAD

**Issue by PinkDev1** [py2exe/py2exe#96]
Please bear with me on this one...

Consider the following code `urllib_bug.py`:
```python
#Code snippet to check for updates in a repository
import requests
from urllib3.exceptions import InsecureRequestWarning
import sys
#List all imported modules
print(sys.modules.keys())

#Check for updates
#Disable plain HTTP warning. We're only getting a version number. Who cares?
#https://stackoverflow.com/questions/15445981/how-do-i-disable-the-security-certificate-check-in-python-requests
#https://github.com/PyCQA/pylint/issues/4584
requests.packages.urllib3.disable_warnings(category=InsecureRequestWarning) # pylint: disable=no-member
updateCheck = requests.get('http://api.github.com/repos/PinkDev1/Terraria-Colourfull-Chat/releases/latest', verify=False)
print("50/50 passed!")
```

and the following `setup.py`:
```python
from distutils.core import setup
import py2exe
setup(
    console = ["urllib_bug.py"],
    options = {"py2exe": {"bundle_files": 1, "compressed": True, "optimize": 2}},
    zipfile = None,
    name = "urllib bug",
    version = "1.0.0"
)
```

and the following explicit_setup.py:
```python
from distutils.core import setup
import py2exe
#ImportError: No module named 'requests.packages.urllib3'; requests.packages is not a package 🤔
#Probably the cause of the inconsistent builds
setup(
    console = ["urllib_bug.py"],
    options = {"py2exe": {"bundle_files": 1, "compressed": True, "optimize": 2, "includes": ["ssl", "_socket", "_ssl", "socket", "selectors", "select", "base64", "binascii", "_hashlib", "urllib3.util.ssltransport", "requests.packages.urllib3.util.ssltransport"]}},
    zipfile = None,
    name = "urllib bug",
    version = "1.0.0"
)
```

---
In the following environment:
- Python 3.7.7
- py2exe 0.10.1.0

# setup.py
The build process always succeeds, **BUT**, when executing the generated `urllib_bug.exe`, two things can happen:
We get the following error
```
Traceback (most recent call last):
  File "urllib3\connectionpool.pyc", line 688, in urlopen
  File "urllib3\connectionpool.pyc", line 280, in _get_conn
  File "urllib3\connectionpool.pyc", line 980, in _new_conn
urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.pyc", line 449, in send
  File "urllib3\connectionpool.pyc", line 756, in urlopen
  File "urllib3\util\retry.pyc", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/PinkDev1/Terraria-Colourfull-Chat/releases/latest (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib_bug.py", line 13, in <module>
    updateCheck = requests.get('http://api.github.com/repos/PinkDev1/Terraria-Colourfull-Chat/releases/latest', verify=False)
  File "requests\api.pyc", line 76, in get
  File "requests\api.pyc", line 61, in request
  File "requests\sessions.pyc", line 542, in request
  File "requests\sessions.pyc", line 677, in send
  File "requests\sessions.pyc", line 677, in <listcomp>
  File "requests\sessions.pyc", line 245, in resolve_redirects
  File "requests\sessions.pyc", line 655, in send
  File "requests\adapters.pyc", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/PinkDev1/Terraria-Colourfull-Chat/releases/latest (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))
```
or, the program successfully gets to line 14 and prints out `50/50 passed!
`

Wheter or not we got the error, seems to depend on the order in which DLLs were copied; On builds where the exe runs successfully, this is the building output:
```
  22 missing Modules
  ------------------
? Cookie                              imported from requests.compat
? OpenSSL                             imported from urllib3.contrib.pyopenssl
? backports                           imported from urllib3.packages.ssl_match_hostname
? brotli                              imported from urllib3.response, urllib3.util.request
? collections.Callable                imported from requests.compat
? collections.Mapping                 imported from requests.compat, urllib3._collections
? collections.MutableMapping          imported from requests.compat, urllib3._collections
? cookielib                           imported from requests.compat
? cryptography                        imported from requests, urllib3.contrib.pyopenssl
? readline                            imported from cmd, code, pdb
? simplejson                          imported from requests.compat
? socks                               imported from urllib3.contrib.socks
? urllib.getproxies                   imported from requests.compat
? urllib.getproxies_environment       imported from requests.compat
? urllib.proxy_bypass                 imported from requests.compat
? urllib.proxy_bypass_environment     imported from requests.compat
? urllib.quote                        imported from requests.compat
? urllib.quote_plus                   imported from requests.compat
? urllib.unquote                      imported from requests.compat
? urllib.unquote_plus                 imported from requests.compat
? urllib.urlencode                    imported from requests.compat
Building 'dist\urllib_bug.exe'.
Copy DLL C:\Program Files\Python37\VCRUNTIME140.dll to dist
Copy DLL C:\Program Files\Python37\DLLs\libssl-1_1.dll to dist
Copy DLL C:\Program Files (x86)\Nmap\libcrypto-1_1.dll to dist
Copy DLL C:\Program Files\Python37\DLLs\libcrypto-1_1.dll to dist
Copy lib file C:\Users\PinkDev1\Documents\GitHub\terrariaColorfullChat\python37venv\lib\site-packages\certifi\cacert.pem to dist
```

and on unsuccessfull exe's, this is the building output:
```
  22 missing Modules
  ------------------
? Cookie                              imported from requests.compat
? OpenSSL                             imported from urllib3.contrib.pyopenssl
? backports                           imported from urllib3.packages.ssl_match_hostname
? brotli                              imported from urllib3.response, urllib3.util.request
? collections.Callable                imported from requests.compat
? collections.Mapping                 imported from requests.compat, urllib3._collections
? collections.MutableMapping          imported from requests.compat, urllib3._collections
? cookielib                           imported from requests.compat
? cryptography                        imported from requests, urllib3.contrib.pyopenssl
? readline                            imported from cmd, code, pdb
? simplejson                          imported from requests.compat
? socks                               imported from urllib3.contrib.socks
? urllib.getproxies                   imported from requests.compat
? urllib.getproxies_environment       imported from requests.compat
? urllib.proxy_bypass                 imported from requests.compat
? urllib.proxy_bypass_environment     imported from requests.compat
? urllib.quote                        imported from requests.compat
? urllib.quote_plus                   imported from requests.compat
? urllib.unquote                      imported from requests.compat
? urllib.unquote_plus                 imported from requests.compat
? urllib.urlencode                    imported from requests.compat
Building 'dist\urllib_bug.exe'.
Copy DLL C:\Program Files\Python37\VCRUNTIME140.dll to dist
Copy DLL C:\Program Files\Python37\DLLs\libcrypto-1_1.dll to dist
Copy DLL C:\Program Files (x86)\Nmap\libcrypto-1_1.dll to dist
Copy DLL C:\Program Files\Python37\DLLs\libssl-1_1.dll to dist
Copy lib file C:\Users\PinkDev1\Documents\GitHub\terrariaColorfullChat\python37venv\lib\site-packages\certifi\cacert.pem to dist
```

If you run a diff, you'll notice that the libcrypto from nmap always gets imported. On the **working** one, python's libcrypto is copied LAST, overwriting the one from nmap, BUT on the broken one, python's libcrypto is imported FIRST, therefor, getting overwritten by nmap's.

Getting a different result may take up to 5 (or more) re-builds.

**If after building a broken exe, you build a working exe, the previously broken one will magically work.**
**If after building a working exe, you build a broken exe, the previously working one will magically NOT work anymore** 

I know what you're thinking. No, they're not the exact same file; their MD5 hashes are different: 
Hashes of the WORKING one:
- CRC32: C2882D77
- MD5: 479CA8EB86B4D2537ED9C0352F36B439
- SHA-1: A46D6834F9B5DF005DBA8B1F4C9EE98FCDBC3700
- SHA-256: 545EAD0A9320A8CBF1A05775E26759827B038DB146262D5AEBAD68FA7B7F0A20

hashes of the BROKEN one:
- CRC32: 73DC909F
- MD5: C6F0129C3F1AEA697C8278EB87D1B0E5
- SHA-1: 6ED4FAEE405B0FB3A222886BB659E12B038DC41B
- SHA-256: EDE584349B6615BF565F3B3B6E9876077E457ADC4CE4605BA41AFD5EE96F5F38

# explicit_setup.py
The build **always** fails with the following error:
```
running py2exe
Traceback (most recent call last):
  File "C:\Users\PinkDev1\Documents\GitHub\terrariaColorfullChat\python37venv\lib\site-packages\py2exe\mf3.py", line 310, in _find_and_load
    path = parent_module.__path__
AttributeError: 'Module' object has no attribute '__path__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\explicit_setup.py", line 10, in <module>
    version = "1.0.0"
  File "C:\Program Files\Python37\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Program Files\Python37\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Program Files\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\PinkDev1\Documents\GitHub\terrariaColorfullChat\python37venv\lib\site-packages\py2exe\distutils_buildexe.py", line 192, in run
    self._run()
  File "C:\Users\PinkDev1\Documents\GitHub\terrariaColorfullChat\python37venv\lib\site-packages\py2exe\distutils_buildexe.py", line 272, in _run
    builder.analyze()
  File "C:\Users\PinkDev1\Documents\GitHub\terrariaColorfullChat\python37venv\lib\site-packages\py2exe\runtime.py", line 168, in analyze
    mf.import_hook(modname)
  File "C:\Users\PinkDev1\Documents\GitHub\terrariaColorfullChat\python37venv\lib\site-packages\py2exe\mf3.py", line 122, in import_hook
    module = self._gcd_import(name)
  File "C:\Users\PinkDev1\Documents\GitHub\terrariaColorfullChat\python37venv\lib\site-packages\py2exe\mf3.py", line 276, in _gcd_import
    return self._find_and_load(name)
  File "C:\Users\PinkDev1\Documents\GitHub\terrariaColorfullChat\python37venv\lib\site-packages\py2exe\mf3.py", line 290, in _find_and_load
    self._gcd_import(parent)
  File "C:\Users\PinkDev1\Documents\GitHub\terrariaColorfullChat\python37venv\lib\site-packages\py2exe\mf3.py", line 276, in _gcd_import
    return self._find_and_load(name)
  File "C:\Users\PinkDev1\Documents\GitHub\terrariaColorfullChat\python37venv\lib\site-packages\py2exe\mf3.py", line 290, in _find_and_load
    self._gcd_import(parent)
  File "C:\Users\PinkDev1\Documents\GitHub\terrariaColorfullChat\python37venv\lib\site-packages\py2exe\mf3.py", line 276, in _gcd_import
    return self._find_and_load(name)
  File "C:\Users\PinkDev1\Documents\GitHub\terrariaColorfullChat\python37venv\lib\site-packages\py2exe\mf3.py", line 318, in _find_and_load
    raise ImportError(msg, name=name)
ImportError: No module named 'requests.packages.urllib3'; requests.packages is not a package
```

---
In the following environment:
- Python 3.9.0
- py2exe 0.10.4.0

# setup.py
The build takes a couple seconds more, but always succeeds with the same output:
```
  6 missing Modules
  ------------------
? _posixshmem                         imported from multiprocessing.resource_tracker, multiprocessing.shared_memory
? _testinternalcapi                   imported from test.support
? readline                            imported from cmd, code, pdb
? requests                            imported from __SCRIPT__
? resource                            imported from test.support
? urllib3                             imported from __SCRIPT__
Building 'dist\urllib_bug.exe'.
Copy DLL C:\Program Files\Python39\DLLs\tcl86t.dll to dist
Copy DLL C:\Program Files\Python39\DLLs\tk86t.dll to dist
Copy DLL C:\Program Files\Python39\DLLs\libcrypto-1_1.dll to dist
Copy DLL C:\Program Files\Python39\DLLs\libffi-7.dll to dist
```

BUT, in this case, when executing the generated `urllib_bug.exe`, we ALWAYS get this error:
```
  File "urllib_bug.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

# explicit_setup.py

The build **always** fails with the following error:
```
Traceback (most recent call last):
  File "C:\Users\PinkDev1\Desktop\urllib_bug\explicit_setup.py", line 5, in <module>
    setup(
  File "C:\Program Files\Python39\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Program Files\Python39\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Program Files\Python39\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\PinkDev1\Desktop\urllib_bug\smallVenv\lib\site-packages\py2exe\distutils_buildexe.py", line 192, in run
    self._run()
  File "C:\Users\PinkDev1\Desktop\urllib_bug\smallVenv\lib\site-packages\py2exe\distutils_buildexe.py", line 272, in _run
    builder.analyze()
  File "C:\Users\PinkDev1\Desktop\urllib_bug\smallVenv\lib\site-packages\py2exe\runtime.py", line 168, in analyze
    mf.import_hook(modname)
  File "C:\Users\PinkDev1\Desktop\urllib_bug\smallVenv\lib\site-packages\py2exe\mf34.py", line 104, in import_hook
    module = self._gcd_import(name)
  File "C:\Users\PinkDev1\Desktop\urllib_bug\smallVenv\lib\site-packages\py2exe\mf34.py", line 258, in _gcd_import
    return self._find_and_load(name)
  File "C:\Users\PinkDev1\Desktop\urllib_bug\smallVenv\lib\site-packages\py2exe\mf34.py", line 272, in _find_and_load
    self._gcd_import(parent)
  File "C:\Users\PinkDev1\Desktop\urllib_bug\smallVenv\lib\site-packages\py2exe\mf34.py", line 258, in _gcd_import
    return self._find_and_load(name)
  File "C:\Users\PinkDev1\Desktop\urllib_bug\smallVenv\lib\site-packages\py2exe\mf34.py", line 272, in _find_and_load
    self._gcd_import(parent)
  File "C:\Users\PinkDev1\Desktop\urllib_bug\smallVenv\lib\site-packages\py2exe\mf34.py", line 258, in _gcd_import
    return self._find_and_load(name)
  File "C:\Users\PinkDev1\Desktop\urllib_bug\smallVenv\lib\site-packages\py2exe\mf34.py", line 328, in _find_and_load
    raise ImportError(name)
ImportError: urllib3
```
---

- "smallVenv" is the name of the venv with Python 3.9.0
- "python37venv" is the name of the venv with python 3.7.7

I made `explicit_build.py` by doing a _diff_ on the `sys.modules.keys()` (imported modules) output from the working vs broken exe's built with v0.10.1.0

All of three of the binaries uploaded here were compiled from the exact same source code:
https://mega.nz/folder/BwwkkRxb#9m38O875qn7mEPwvkRyfwA

---
# WTF?
It may be tempting to blame the nmap DLL, but this whole thing plants many difficult questions:
- Why does the DLL copying order vary from build-to-build?
- Why does the exe work when nmap DLLs are not included at all, if that's what seemed to work on v0.10.1.0?
- Why does **pylint** also have an issue with the `requests.packages` library? (see: https://github.com/PyCQA/pylint/issues/4584)
- Why are the hashes of the python 3.7.7 builds different from eachother, even though DLLs seem to break them both at the same time?

I felt like a madman for re-compiling the same program and expecting different results, but appearently this is a bug that exists 🤷‍♂️

**Comment by albertosottile** [comment]
Hello,
thanks for this thorough investigation. Unfortunately, I do not have the time now to help you as you would deserve. However, I can briefly answer to the first two questions. 

> Why does the DLL copying order vary from build-to-build?
Why does the exe work when nmap DLLs are not included at all, if that's what seemed to work on v0.10.1.0?

The DLL order changes depending on which component of `dllfinder` finds the library and when. There are two mechanisms in `py2exe` to detect linked libraries: via `BindImageEx` and via `pefile`. In short, the former is more accurate but can miss many libraries, while the latter usuall catches all the needed dependencies but can also get some unnecessary links. 

In your case, most likely `pefile` is finding `libcrypto-1_1.dll` in the nmap folder and it is saying that your code is linked to that, whereas `BindImageEx` is correctly saying that your code is linked to the `libcrypto-1_1.dll` file shipped by Python.

Unfortunately, `pefile` looks in everything that is in your `PATH` environment library. Hence, until I code a more clever way to fix this condition, if you absolutely want to have consistent builds, the only solution is to alter the `PATH` of your console before building and remove the nmap folder from it. You can also achieve the same result by building in a dedicated reproducable environment, e.g. a Docker container or a VM.

**Comment by PinkDev1** [comment]
I don't know how you did it man, but the builds are consistent now, using py2exe '0.11.0.1'! Well done 😁
